<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Albums
[
<!ELEMENT Albums (artist+)>
<!ELEMENT artist (album)>
<!ATTLIST artist personorgroup CDATA #REQUIRED>
<!ATTLIST artist groupmembernames CDATA #REQUIRED>
<!ATTLIST artist artistorgroupcountry CDATA #REQUIRED>
<!ATTLIST artist careerBegin CDATA #REQUIRED>
<!ATTLIST artist careerend CDATA #REQUIRED>
<!ATTLIST artist artistName CDATA #REQUIRED>
<!ELEMENT album (albumArt, releases, Songs, producersMixersSongwritersEngineers*)>
<!ELEMENT releases (release+)>
<!ELEMENT release ANY>
<!ELEMENT Songs (song+)>
<!ELEMENT song ANY>
<!ELEMENT producersMixersSongwritersEngineers (producers*, engineersMixers, songwriters, masteringEngineer)>
<!ELEMENT engineersMixers (#PCDATA)>
<!ELEMENT songwriters (#PCDATA)>
<!ELEMENT masteringEngineer (#PCDATA)>
<!ELEMENT producers (#PCDATA)>
<!ATTLIST release release CDATA #REQUIRED>
<!ATTLIST release releasedate CDATA #REQUIRED>
<!ATTLIST release recordlabel CDATA #REQUIRED>
<!ATTLIST release recordlabelcatalognumber CDATA #REQUIRED>
<!ATTLIST release  barcodenumber CDATA #REQUIRED>
<!ATTLIST release  country CDATA #REQUIRED>
<!ATTLIST release  format CDATA #REQUIRED>
<!ATTLIST album albumCategory CDATA #REQUIRED>
<!ATTLIST album albumName CDATA #REQUIRED>
<!ATTLIST song songposition CDATA #REQUIRED>
<!ATTLIST song songlength CDATA #REQUIRED>
<!ATTLIST song songcomposersandwriters CDATA #REQUIRED>
<!ATTLIST song songName CDATA #REQUIRED>

<!ELEMENT albumArt (#PCDATA)>






]
>
<Albums>
        <artist 
        personorgroup= "person" 
        groupmembernames= "N/A" 
        artistorgroupcountry= "United States" 
        careerBegin= "2015" careerend= "N/A"
        artistName = "Cardi B">
                <album albumCategory = "Grammy Nominee"
                       albumName = "Invasion of Privacy">
                    <albumArt>
                        Cardi B.jpg
                        <!-- Found from albumartexchange.com -->
                    </albumArt>
                    <releases>
                        <release 
                            release = "Invasion of Privacy (clean lyrics)"
                            releasedate = "2018-04-05"
                            recordlabel= "Atlantic (Warner Music imprint), KSR Group"
                            recordlabelcatalognumber = "N/A"
                            barcodenumber = "075679873675"
                            country = "US"
                            format = "Digital Media">
                        </release>
                        <release
                            release = "Invasion of Privacy (explicit)"
                            releasedate = "2018-04-05 / 2018-04-06 / 2018-04-06"
                            recordlabel= "Atlantic (Warner Music imprint), KSR Group"
                            recordlabelcatalognumber = "N/A"
                            barcodenumber = "075679873682"
                            country = "XW
                            CA
                            US"
                            format = "Digital Media">
                        </release>
                    </releases>
                    <Songs>
                        <song 
                            songposition = "1" 
                            songlength = "3:51" 
                            songcomposersandwriters = "Sean Allen / Belcalis Almanzar / Maurice Jordan / Jermaine Preyan / James SwanQo / Anthony Tucker / Robert Williams"
                            songName = "Get Up 10">
                        </song>
                        <song 
                            songposition = "2" 
                            songlength = "4:23" 
                            songcomposersandwriters = "Belcalis Almanzar / Kirsnick Ball / Kiari Cephus / Joshua Cross / Quavious Marshall"
                            songName = "Drip (feat. Migos)">
                        </song>
                        <song 
                            songposition = "3" 
                            songlength = "3:01" 
                            songcomposersandwriters = "Belcalis Almanzar / James Foye III / Philip Coleman, Jr. / Austin Owens / Jordan Thorpe"
                            songName = "Bickenhead">
                        </song>
                        <song 
                            songposition = "4" 
                            songlength = "3:43" 
                            songcomposersandwriters = "Belcalis Almanzar / Laquan Green / J. White Did It / Dieuson Octave / Klenord Raphael / Jordan Thorpe / Jermaine White"
                            songName = "Bodak Yellow">
                        </song>
                        <song 
                            songposition = "5" 
                            songlength = "3:30" 
                            songcomposersandwriters = "Belcalis Almanzar / Alan Bergman / Marilyn Bergman / Dennis Coles / Robert Diggs / Adam Feeney / Gary Grice / Marvin Hamlisch / Lamont Hawkins / Anderson Hernandez / Lauryn Hill / Jason Hunter / Russell Jones / Matthew Samuels / Clifford Smith / Jordan Thorpe / U-God / Corey Woods"
                            songName = "Be Careful">
                        </song>
                        <song 
                            songposition = "6" 
                            songlength = "4:44" 
                            songcomposersandwriters = "Belcalis Almanzar / Chancelor Bennett / Allen Ritter / Matthew Samuels"
                            songName = "Best Life">
                        </song>
                        <song 
                            songposition = "7" 
                            songlength = "4:13" 
                            songcomposersandwriters = "Belcalis Almanzar / José Álvaro Osorio Balvin / Benito Antonio Martinez Ocasio / Tony Pabon / Manny Rodriguez"
                            songName = "I Like It">
                        </song>
                        <song 
                            songposition = "8" 
                            songlength = "2:57" 
                            songcomposersandwriters = "Belcalis Almanzar / Khari Cain / Nija Charles / Kehlani Parrish / Mike Riley"
                            songName = "Ring">
                        </song>
                        <song 
                            songposition = "9" 
                            songlength = "3:49" 
                            songcomposersandwriters = "Belcalis Almanzar / Jordan Thorpe / Jermaine White"
                            songName = "Money Bag">
                        </song>
                        <song 
                            songposition = "10" 
                            songlength = "3:44" 
                            songcomposersandwriters = "Shayaa Bin Abraham-Joseph / Belcalis Almanzar / Samuel Gloade / Darryl McCorkell"
                            songName = "Bartier Cardi (feat. 21 Savage)">
                        </song>
                        <song 
                            songposition = "11" 
                            songlength = "3:50" 
                            songcomposersandwriters = "Belcalis Almanzar / Keenon Jackson / Leslie Andre Wakefield Jr. / Dijon McFarlane"
                            songName = "She Bad">
                        </song>
                        <song 
                            songposition = "12" 
                            songlength = "3:08" 
                            songcomposersandwriters = "Belcalis Almanzar / Benjamin Levin / Alexandra Tamposi / Justin Tranter / Andrew Wotman"
                            songName = "Thru Your Phone">
                        </song>
                        <song 
                            songposition = "13" 
                            songlength = "3:20" 
                            songcomposersandwriters = "Belcalis Almanzar / Nija Charles / Kevin Gomringer / Tim Gomringer / Shane Lindstrom / Solana Rowe"
                            songName = "I Do">
                        </song>
                    </Songs>
                    <producersMixersSongwritersEngineers>
                        <engineersMixers>
                            Leslie Brathwaite &amp; Evan LaRay
                        </engineersMixers>
                        <songwriters>
                            Belcalis Almanzar &amp; Jorden Thorpe
                        </songwriters>
                        <masteringEngineer>
                            Colin Leonard
                        </masteringEngineer>
                    </producersMixersSongwritersEngineers>
                </album>
        </artist>
        
    <artist
        personorgroup= "person" 
        groupmembernames= "N/A" 
        artistorgroupcountry= "United States" 
        careerBegin= "2004" careerend= "N/A"
        artistName = "Brandi Carlile">
            
            <album
                albumCategory = "Grammy_Nominee"
                albumName = "By The Way, I Forgive You">
                
                <albumArt>
                    Brandi Carlile.jpg
                    <!-- Found from albumartexchange.com -->
                </albumArt>
                
                <releases>
                    <release 
                        release = "By the Way, I Forgive You"
                        releasedate = "2018-02-16"
                        recordlabel= "Elektra (1950–1989, revived 2009–06-01; read annotations before use), Low Country Sound"
                        recordlabelcatalognumber = "565226-2"
                        barcodenumber = "075678659188"
                        country = "US"
                        format = "CD">
                    </release>
                    <release 
                        release = "By the Way, I Forgive You (mastered for iTunes)"
                        releasedate = "2018-02-16"
                        recordlabel= "Elektra (1950–1989, revived 2009–06-01; read annotations before use)"
                        recordlabelcatalognumber = "N/A"
                        barcodenumber = "075679885449"
                        country = "US"
                        format = "Digital Media">
                    </release>
                </releases>
                <Songs>
                    <song 
                        songposition = "1" 
                        songlength = "4:01" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "Everytime I Hear That Song">
                    </song>
                    <song 
                        songposition = "2" 
                        songlength = "4:39" 
                        songcomposersandwriters = "Brandi Carlile / Dave Cobb / Phil Hanseroth / Tim Hanseroth"
                        songName = "The Joke">
                    </song>
                    <song 
                        songposition = "3" 
                        songlength = "4:22" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "Hold Out Your Hand">
                    </song>
                    <song 
                        songposition = "4" 
                        songlength = "3:16" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "The Mother">
                    </song>
                    <song 
                        songposition = "5" 
                        songlength = "4:07" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "Whatever You Do">
                    </song>
                    <song 
                        songposition = "6" 
                        songlength = "4:43" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "Fulton County Jane Doe">
                    </song>
                    <song 
                        songposition = "7" 
                        songlength = "4:28" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "Sugartooth">
                    </song>
                    <song 
                        songposition = "8" 
                        songlength = "3:51" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "Most of All">
                    </song>
                    <song 
                        songposition = "9" 
                        songlength = "4:06" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "Harder to Forgive">
                    </song>
                    <song 
                        songposition = "10" 
                        songlength = "5:47" 
                        songcomposersandwriters = "Brandi Carlile / Phil Hanseroth / Tim Hanseroth"
                        songName = "Party of One">
                    </song>
                </Songs>
                <producersMixersSongwritersEngineers>
                    <producers>
                    Dave Cobb &amp; Shooter Jennings
                    </producers>
                    <engineersMixers>
                    Dave Cobb &amp; Eddie Spear
                    </engineersMixers>
                    <songwriters>
                    Brandi Carlile, Phil Hanseroth &amp; Tim Hanseroth
                    </songwriters>
                    <masteringEngineer>
                    Pete Lyman
                    </masteringEngineer>
                </producersMixersSongwritersEngineers>
            </album>
    </artist>
    
    <artist
        personorgroup= "person" 
        groupmembernames= "N/A" 
        artistorgroupcountry= "United States" 
        careerBegin= "2001" careerend= "N/A"
        artistName = "Drake">
            
            <album
                albumName = "Scorpion"
                albumCategory = "Grammy_Nominee">
                
                <albumArt>
                    Drake.jpg
                    <!-- Found from albumartexchange.com -->
                </albumArt>
                
                <releases>
                    <release 
                        release = "Scorpion (clean lyrics)"
                        releasedate = "2018-06-29"
                        recordlabel= "Cash Money Records, Young Money Entertainment"
                        recordlabelcatalognumber = "N/A"
                        barcodenumber = "602567879152"
                        country = "US"
                        format = "2×Digital Media">
                    </release>
                    <release 
                        release = "Scorpion (explicit)"
                        releasedate = "2018-06-29"
                        recordlabel= "Cash Money Records, Young Money Entertainment"
                        recordlabelcatalognumber = "N/A"
                        barcodenumber = "602567879121"
                        country = "XW"
                        format = "2×Digital Media">
                    </release>
                    <release 
                        release
                        = "Scorpion"
                        releasedate = "2018"
                        recordlabel= "Cash Money Records, Republic Records (a division of UMG Recordings, Inc.)"
                        recordlabelcatalognumber = "00602567863182"
                        barcodenumber = "602567863182"
                        country = "NL"
                        format = "2×CD">
                    </release>
                </releases>
                <Songs>
                        <song
                            songposition = "1" 
                            songlength = "2:16" 
                            songcomposersandwriters = "Aubrey Graham / Manuel Landy / Klaus Netzle / Noah Shebib / Dion Wilson"
                            songName = "Survival">
                        </song>
                        <song 
                            songposition = "2" 
                            songlength = "3:58" 
                            songcomposersandwriters = "Brytavious Chambers / Aubrey Graham / Dion Wilson"
                            songName = "Nonstop">
                        </song>
                        <song 
                            songposition = "3" 
                            songlength = "3:04" 
                            songcomposersandwriters = "Jahron Brathwaite / Gary Fountaine / Aubrey Graham"
                            songName = "Elevate">
                        </song>
                        <song 
                            songposition = "4" 
                            songlength = "5:02" 
                            songcomposersandwriters = "Mariah Carey / Robert Clivillés / Dennis Coles / Andrew Gowie / Aubrey Graham / Noah Shebib / Dion Wilson"
                            songName = "Emotionless">
                        </song>
                        <song 
                            songposition = "5" 
                            songlength = "3:18" 
                            songcomposersandwriters = "Aubrey Graham / Daveon Jackson / Brock Korsan / Ronald LaTour / Matthew Samuels / Noah Shebib"
                            songName = "God's Plan">
                        </song>
                        <song 
                            songposition = "6" 
                            songlength = "3:34" 
                            songcomposersandwriters = "Aubrey Graham / Jordan Ortiz"
                            songName = "I'm Upset">
                        </song>
                        <song 
                            songposition = "7" 
                            songlength = "3:15" 
                            songcomposersandwriters = "Aubrey Graham / Matthew O'Brien / Arthur Ross / Matthew Samuels / Jahaan Sweet / Abrim Tilmon / Leon Ware"
                            songName = "8 Out of 10">
                        </song>
                        <song 
                            songposition = "8" 
                            songlength = "3:25" 
                            songcomposersandwriters = "Dave Atkinson / Samuel Barnes / Anthony Cruz / Aubrey Graham / Nasir Jones / Tavoris Hollins, Jr. / Inga Marchand / Cory McKay / Jean-Claude Olivier / Allen Ritter / Matthew Samuels / Asheley Turner"
                            songName = "Mob Ties">
                        </song>
                        <song 
                            songposition = "9" 
                            songlength = "2:43" 
                            songcomposersandwriters = "Max Eberhardt / Aubrey Graham"
                            songName = "Can't Take a Joke">
                        </song>
                        <song 
                            songposition = "10" 
                            songlength = "3:36" 
                            songcomposersandwriters = "Maneesh Bidaye / Aubrey Graham / Chris Martin"
                            songName = "Sandra's Rose">
                        </song>
                        <song 
                            songposition = "11" 
                            songlength = "3:43" 
                            songcomposersandwriters = "Paul Beauregard / Leroy Bonner / Dwayne Carter / Aubrey Graham / O'Shea Jackson / Marshall Jones / Ralph Middlebrooks / Walter Morisson / Andrew Noland / Gregory Webster / Andre Young"
                            songName = "Talk Up">
                        </song>
                        <song 
                            songposition = "12" 
                            songlength = "3:46" 
                            songcomposersandwriters = "Stephen Garrett / Aubrey Graham / Raynford Humphrey / Nima Jahanbin / Paimon Jahanbin / Joseph W. Lane Jr. / Timothy Mosley / Jeffrey Williams"
                            songName = "Is There More">
                        </song>
                        <song 
                            songposition = "13" 
                            songlength = "3:26" 
                            songcomposersandwriters = "Aubrey Graham / Noah Shebib"
                            songName = "Peak">
                        </song>    
                        <song
                            songposition = "14" 
                            songlength = "4:07" 
                            songcomposersandwriters = "Harley Arsenault / Maneesh Bidaye / Aubrey Graham / Paul Jefferies / Noah Shebib / Dion Wilson"
                            songName = "Summer Games">
                        </song>
                        <song 
                            songposition = "15" 
                            songlength = "4:22" 
                            songcomposersandwriters = "Harley Arsenault / Maneesh Bidaye / Aubrey Graham / Paul Jefferies / Noah Shebib / Dion Wilson"
                            songName = "Jaded">
                        </song>
                        <song 
                            songposition = "16" 
                            songlength = "3:30" 
                            songcomposersandwriters = "Alan Bergman / Marilyn Bergman / Dennis Coles / Robert Diggs / Aubrey Graham / Gary Grice / Orville Hall / Marvin Hamlisch / Lamont Hawkins / Lauryn Hill / Jason Hunter / Russell Jones / Shane Lindstrom / Phillip Price / Glenshie Rowe / Noah Shebib / Clifford Smith / Byron Thomas / Bryan Williams / Corey Woods"
                            songName = "Nice for What">
                        </song>
                        <song 
                            songposition = "17" 
                            songlength = "3:02" 
                            songcomposersandwriters = "Noel Cadastre / James Fauntleroy / Aubrey Graham"
                            songName = "Finesse">
                        </song>
                        <song
                            songposition = "18" 
                            songlength = "3:27" 
                            songcomposersandwriters = "Jahron Brathwaite / Leonard Caston / Aubrey Graham / Anita Poree / Matthew Samuels / Jahaan Sweet / Dalton Tennant"
                            songName = "Ratchet Happy Birthday">
                        </song>
                        <song
                            songposition = "19" 
                            songlength = "2:37" 
                            songcomposersandwriters = "Noel Cadastre / Aubrey Graham / John Hyszko / Onika Maraj"
                            songName = "That's How You Feel">
                        </song>
                        <song
                            songposition = "20" 
                            songlength = "2:42" 
                            songcomposersandwriters = "Aubrey Graham / Ramon Ibanga / Demario Priester / Nayvadius Wilburn"
                            songName = "Blue Tint">
                        </song>
                        <song
                            songposition = "21" 
                            songlength = "3:37" 
                            songcomposersandwriters = "Caresha Brownlee / Dwayne Carter / Stephen Garrett / Aubrey Graham / Orville Hall / Darius Harrison / Jatavia Johnson / Renetta Lowe-Bridgewater / Phillip Price / James Scheffer / Benny Workman / Rex Zamor"
                            songName = "In My Feelings">
                        </song>
                        <song
                            songposition = "22" 
                            songlength = "4:05" 
                            songcomposersandwriters = "Paul Anka / Negin Djafari / Aubrey Graham / Michael Jackson / Paul Jefferies / Nana Rogues / Noah Shebib"
                            songName = "Don't Matter to Me">
                        </song>   
                        <song
                            songposition = "23" 
                            songlength = "4:49" 
                            songcomposersandwriters = "Stephen Garrett / Aubrey Graham / Tyrone Griffin / Musze / Melvin Ragin / Noah Shebib"
                            songName = "After Dark">
                        </song>
                        <song
                            songposition = "24" 
                            songlength = "3:39" 
                            songcomposersandwriters = "Alan Bergman / Marilyn Bergman / Aubrey Graham / Michel Legrand / Matthew Samuels / Noah Shebib / Jahaan Sweet"
                            songName = "Final Fantasy">
                        </song>
                        <song 
                            songposition = "25" 
                            songlength = "5:09" 
                            songcomposersandwriters = "Michael Archer / Aubrey Graham / Nathan Morris / Raphael Saadiq / Shawn Stockman / Josh Valle / Tyler Williams"
                            songName = "March 14">
                        </song>
                </Songs>
                <producersMixersSongwritersEngineers>
                    <engineersMixers>
                    Noel Cadastre, Noel "Gadget" Campbell &amp; Noah Shebib
                    </engineersMixers>
                    <songwriters>
                    Aubrey Graham &amp; Noah Shebib
                    </songwriters>
                    <masteringEngineer>
                    Chris Athens
                    </masteringEngineer>
                </producersMixersSongwritersEngineers>
            </album>   
    </artist>        
    
    <artist
        personorgroup= "person" 
        groupmembernames= "N/A" 
        artistorgroupcountry= "United States" 
        careerBegin= "2009" careerend= "N/A"
        artistName = "H.E.R.">
        
        <album
            albumName = "H.E.R."
            albumCategory = "Grammy_Nominee">
            <albumArt>
                H.E.R..jpg
                <!-- Found from albumartexchange.com -->
            </albumArt>
            
            <releases>
                <release
                    release = "H.E.R. (Mastered for iTunes)"
                    releasedate = "2017-10-20"
                    recordlabel= "RCA (RCA Records: simple ‘RCA’ or 'RCA' with lightning bolt in circle)"
                    recordlabelcatalognumber = "N/A"
                    barcodenumber = "886446799513"
                    country = "US"
                    format = "Digital Media">
                </release>
            </releases>
            
            <Songs>
                    <song 
                        songposition = "1" 
                        songlength = "3:45" 
                        songcomposersandwriters = "N/A"
                        songName = "Losing">
                    </song>
                    <song
                        songposition = "2" 
                        songlength = "2:15" 
                        songcomposersandwriters = "N/A"
                        songName = "Wait for It">
                    </song>
                    <song
                        songposition = "3" 
                        songlength = "3:38" 
                        songcomposersandwriters = "N/A"
                        songName = "Facts">
                    </song>
                    <song
                        songposition = "4" 
                        songlength = "2:58" 
                        songcomposersandwriters = "N/A"
                        songName = "U">
                    </song>
                    <song
                        songposition = "5" 
                        songlength = "3:20" 
                        songcomposersandwriters = "N/A"
                        songName = "Focus">
                    </song>
                    <song 
                        songposition = "6" 
                        songlength = "5:04" 
                        songcomposersandwriters = "N/A"
                        songName = "Jungle">
                    </song>
                    <song 
                        songposition = "7" 
                        songlength = "2:58" 
                        songcomposersandwriters = "N/A"
                        songName = "Pigment">
                    </song>
                    <song 
                        songposition = "8" 
                        songlength = "2:40" 
                        songcomposersandwriters = "N/A"
                        songName = "Every Kind of Way">
                    </song>
                    <song 
                        songposition = "9" 
                        songlength = "2:52" 
                        songcomposersandwriters = "N/A"
                        songName = "Say It Again">
                    </song>
                    <song
                        songposition = "10" 
                        songlength = "2:49" 
                        songcomposersandwriters = "N/A"
                        songName = "Still Down">
                    </song>
                    <song 
                        songposition = "11" 
                        songlength = "3:34" 
                        songcomposersandwriters = "N/A"
                        songName = "Avenue">
                    </song>
                    <song 
                        songposition = "12" 
                        songlength = "4:10" 
                        songcomposersandwriters = "N/A"
                        songName = "Gone Away">
                    </song>
                    <song
                        songposition = "13" 
                        songlength = "3:33" 
                        songcomposersandwriters = "N/A"
                        songName = "I Won't">
                    </song>