=== vinnieroy1998/2018-2019-Grammy-Albums---XML/XML w: Internal and External DTD/royv_project1-3.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Albums (artist+)>
<!ELEMENT artist (album)>
<!ATTLIST artist personorgroup CDATA #REQUIRED>
<!ATTLIST artist groupmembernames CDATA #REQUIRED>
<!ATTLIST artist artistorgroupcountry CDATA #REQUIRED>
<!ATTLIST artist careerBegin CDATA #REQUIRED>
<!ATTLIST artist careerend CDATA #REQUIRED>
<!ATTLIST artist artistName CDATA #REQUIRED>
<!ATTLIST artist artistName CDATA #REQUIRED>
<!ELEMENT album (albumArt, releases, Songs, producersMixersSongwritersEngineers*)>
<!ELEMENT releases (release+)>
<!ELEMENT release ANY>
<!ELEMENT Songs (song+)>
<!ELEMENT song ANY>
<!ELEMENT producersMixersSongwritersEngineers (producers*, engineersMixers, songwriters, masteringEngineer)>
<!ELEMENT engineersMixers (#PCDATA)>
<!ELEMENT songwriters (#PCDATA)>
<!ELEMENT masteringEngineer (#PCDATA)>
<!ELEMENT producers (#PCDATA)>
<!ATTLIST release release CDATA #REQUIRED>
<!ATTLIST release releasedate CDATA #REQUIRED>
<!ATTLIST release recordlabel CDATA #REQUIRED>
<!ATTLIST release recordlabelcatalognumber CDATA #REQUIRED>
<!ATTLIST release  barcodenumber CDATA #REQUIRED>
<!ATTLIST release  country CDATA #REQUIRED>
<!ATTLIST release  format CDATA #REQUIRED>
<!ATTLIST album albumCategory CDATA #REQUIRED>
<!ATTLIST album albumName CDATA #REQUIRED>
<!ATTLIST album sku CDATA #REQUIRED>
<!ATTLIST album type CDATA #REQUIRED>
<!ATTLIST song songposition CDATA #REQUIRED>
<!ATTLIST song songlength CDATA #REQUIRED>
<!ATTLIST song songcomposersandwriters CDATA #REQUIRED>
<!ATTLIST song songName CDATA #REQUIRED>
<!ATTLIST song sku CDATA #REQUIRED>
<!ATTLIST song type CDATA #REQUIRED>
<!ATTLIST song albumref CDATA #REQUIRED>
<!ELEMENT albumArt (#PCDATA)>

=== vinnieroy1998/2018-2019-Grammy-Albums---XML/royv_project1-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Albums SYSTEM "royv_project1-3.dtd">

<Albums>
        <artist 
        personorgroup= "person" 
        groupmembernames= "N/A" 
        artistorgroupcountry= "United States" 
        careerBegin= "2015" careerend= "N/A"
        artistName = "Cardi B">
                <album albumCategory = "Grammy Nominee"
                       albumName = "Invasion of Privacy"
                       sku = "K315SPR19A"
                       type = "album">
                    <albumArt>
                        Cardi B.jpg
                        <!-- Found from albumartexchange.com -->
                    </albumArt>
                    <releases>
                        <release 
                            release = "Invasion of Privacy (clean lyrics)"
                            releasedate = "2018-04-05"
                            recordlabel= "Atlantic (Warner Music imprint), KSR Group"
                            recordlabelcatalognumber = "N/A"
                            barcodenumber = "075679873675"
                            country = "US"
                            format = "Digital Media">
                        </release>
                        <release
                            release = "Invasion of Privacy (explicit)"
                            releasedate = "2018-04-05 / 2018-04-06 / 2018-04-06"
                            recordlabel= "Atlantic (Warner Music imprint), KSR Group"
                            recordlabelcatalognumber = "N/A"
                            barcodenumber = "075679873682"
                            country = "XW
                            CA
                            US"
                            format = "Digital Media">
                        </release>
                    </releases>
                    <Songs>
                        <song 
                            songposition = "1" 
                            songlength = "3:51" 
                            songcomposersandwriters = "Sean Allen / Belcalis Almanzar / Maurice Jordan / Jermaine Preyan / James SwanQo / Anthony Tucker / Robert Williams"
                            songName = "Get Up 10"
                            sku = "K315SPR19A001"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "2" 
                            songlength = "4:23" 
                            songcomposersandwriters = "Belcalis Almanzar / Kirsnick Ball / Kiari Cephus / Joshua Cross / Quavious Marshall"
                            songName = "Drip (feat. Migos)"
                            sku = "K315SPR19A002"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "3" 
                            songlength = "3:01" 
                            songcomposersandwriters = "Belcalis Almanzar / James Foye III / Philip Coleman, Jr. / Austin Owens / Jordan Thorpe"
                            songName = "Bickenhead"
                            sku = "K315SPR19A003"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "4" 
                            songlength = "3:43" 
                            songcomposersandwriters = "Belcalis Almanzar / Laquan Green / J. White Did It / Dieuson Octave / Klenord Raphael / Jordan Thorpe / Jermaine White"
                            songName = "Bodak Yellow"
                            sku = "K315SPR19A004"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "5" 
                            songlength = "3:30" 
                            songcomposersandwriters = "Belcalis Almanzar / Alan Bergman / Marilyn Bergman / Dennis Coles / Robert Diggs / Adam Feeney / Gary Grice / Marvin Hamlisch / Lamont Hawkins / Anderson Hernandez / Lauryn Hill / Jason Hunter / Russell Jones / Matthew Samuels / Clifford Smith / Jordan Thorpe / U-God / Corey Woods"
                            songName = "Be Careful"
                            sku = "K315SPR19A005"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "6" 
                            songlength = "4:44" 
                            songcomposersandwriters = "Belcalis Almanzar / Chancelor Bennett / Allen Ritter / Matthew Samuels"
                            songName = "Best Life"
                            sku = "K315SPR19A006"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "7" 
                            songlength = "4:13" 
                            songcomposersandwriters = "Belcalis Almanzar / José Álvaro Osorio Balvin / Benito Antonio Martinez Ocasio / Tony Pabon / Manny Rodriguez"
                            songName = "I Like It"
                            sku = "K315SPR19A007"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "8" 
                            songlength = "2:57" 
                            songcomposersandwriters = "Belcalis Almanzar / Khari Cain / Nija Charles / Kehlani Parrish / Mike Riley"
                            songName = "Ring"
                            sku = "K315SPR19A008"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "9" 
                            songlength = "3:49" 
                            songcomposersandwriters = "Belcalis Almanzar / Jordan Thorpe / Jermaine White"
                            songName = "Money Bag"
                            sku = "K315SPR19A009"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "10" 
                            songlength = "3:44" 
                            songcomposersandwriters = "Shayaa Bin Abraham-Joseph / Belcalis Almanzar / Samuel Gloade / Darryl McCorkell"
                            songName = "Bartier Cardi (feat. 21 Savage)"
                            sku = "K315SPR19A010"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "11" 
                            songlength = "3:50" 
                            songcomposersandwriters = "Belcalis Almanzar / Keenon Jackson / Leslie Andre Wakefield Jr. / Dijon McFarlane"
                            songName = "She Bad"
                            sku = "K315SPR19A011"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "12" 
                            songlength = "3:08" 
                            songcomposersandwriters = "Belcalis Almanzar / Benjamin Levin / Alexandra Tamposi / Justin Tranter / Andrew Wotman"
                            songName = "Thru Your Phone"
                            sku = "K315SPR19A012"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                        <song 
                            songposition = "13" 
                            songlength = "3:20" 
                            songcomposersandwriters = "Belcalis Almanzar / Nija Charles / Kevin Gomringer / Tim Gomringer / Shane Lindstrom / Solana Rowe"
                            songName = "I Do"
                            sku = "K315SPR19A013"
                            albumref = "K315SPR19A"
                            type = "song">
                        </song>
                    </Songs>
                    <producersMixersSongwritersEngineers>
                        <engineersMixers>
                            Leslie Brathwaite &amp; Evan LaRay
                        </engineersMixers>
                        <songwriters>
                            Belcalis Almanzar &amp; Jorden Thorpe
                        </songwriters>
                        <masteringEngineer>
                            Colin Leonard
                        </masteringEngineer>
                    </producersMixersSongwritersEngineers>
                </album>
        </artist>
        
    <artist
        personorgroup= "person" 
        groupmembernames= "N/A" 
        artistorgroupcountry= "United States" 
        careerBegin= "2004" careerend= "N/A"
        artistName = "Brandi Carlile">
            
            <album
                albumCategory = "Grammy_Nominee"
                albumName = "By The Way, I Forgive You"
                sku = "K315SPR19B"
                type = "album">
                <albumArt>
                    Brandi Carlile.jpg
                    <!-- Found from albumartexchange.com -->
                </albumArt>
                
                <releases>
                    <release 
                        release = "By the Way, I Forgive You"
                        releasedate = "2018-02-16"
